/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.minipc.kiosk;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int custom_progress=0x7f020000;
        public static final int ic_error=0x7f020001;
        public static final int ic_folder=0x7f020002;
        public static final int ic_loading=0x7f020003;
    }
    public static final class id {
        public static final int audio_channel_text=0x7f04004a;
        public static final int btn_add_pc=0x7f040002;
        public static final int btn_close_app=0x7f040050;
        public static final int btn_disconnect=0x7f040005;
        public static final int btn_go_up=0x7f040031;
        public static final int btn_movie_play_pause=0x7f040038;
        public static final int btn_movie_seek_back=0x7f040037;
        public static final int btn_movie_seek_fwd=0x7f040039;
        public static final int btn_movie_stop=0x7f04003c;
        public static final int btn_movie_vol_down=0x7f04003a;
        public static final int btn_movie_vol_up=0x7f04003b;
        public static final int btn_music_library=0x7f04000d;
        public static final int btn_music_playing=0x7f04000b;
        public static final int btn_music_queue=0x7f04000e;
        public static final int btn_music_search=0x7f04000c;
        public static final int btn_next=0x7f04001c;
        public static final int btn_np_like=0x7f04001d;
        public static final int btn_np_playlist=0x7f04001e;
        public static final int btn_play_pause=0x7f04001b;
        public static final int btn_prev=0x7f04001a;
        public static final int btn_refresh=0x7f040007;
        public static final int btn_repeat=0x7f040024;
        public static final int btn_restart=0x7f04004f;
        public static final int btn_search=0x7f040029;
        public static final int btn_seek_back=0x7f040015;
        public static final int btn_seek_fwd=0x7f040019;
        public static final int btn_shuffle=0x7f040023;
        public static final int btn_shutdown=0x7f04004e;
        public static final int btn_speaker_config=0x7f04004c;
        public static final int btn_theme=0x7f040040;
        public static final int btn_vol_down=0x7f04001f;
        public static final int btn_vol_up=0x7f040022;
        public static final int content_area=0x7f040008;
        public static final int cpu_bar=0x7f040042;
        public static final int cpu_text=0x7f040041;
        public static final int current_path=0x7f040032;
        public static final int disk_bar=0x7f040046;
        public static final int disk_text=0x7f040045;
        public static final int files_list=0x7f040033;
        public static final int gpu_bar=0x7f040048;
        public static final int gpu_text=0x7f040047;
        public static final int ip_list_container=0x7f040001;
        public static final int last_updated_text=0x7f040049;
        public static final int library_content=0x7f04002c;
        public static final int loading_overlay=0x7f040056;
        public static final int loading_text=0x7f040057;
        public static final int movie_browser_view=0x7f040030;
        public static final int movie_info=0x7f04003d;
        public static final int movie_player_view=0x7f040034;
        public static final int movie_time=0x7f040036;
        public static final int movie_title=0x7f040035;
        public static final int music_library=0x7f04002b;
        public static final int music_now_playing=0x7f04000f;
        public static final int music_queue=0x7f04002d;
        public static final int music_search=0x7f040025;
        public static final int music_sub_tabs=0x7f04000a;
        public static final int np_album=0x7f040014;
        public static final int np_art_error=0x7f040011;
        public static final int np_artist=0x7f040013;
        public static final int np_artwork=0x7f040010;
        public static final int np_progress=0x7f040017;
        public static final int np_time_current=0x7f040016;
        public static final int np_time_total=0x7f040018;
        public static final int np_title=0x7f040012;
        public static final int queue_content=0x7f04002e;
        public static final int ram_bar=0x7f040044;
        public static final int ram_text=0x7f040043;
        public static final int screen_connection=0x7f040000;
        public static final int screen_main=0x7f040003;
        public static final int search_input=0x7f040026;
        public static final int search_limit=0x7f040027;
        public static final int search_results=0x7f04002a;
        public static final int search_type_spinner=0x7f040028;
        public static final int seekBar_volume=0x7f040021;
        public static final int status_toast=0x7f040058;
        public static final int tab_bar=0x7f040051;
        public static final int tab_btn_movies=0x7f040053;
        public static final int tab_btn_music=0x7f040052;
        public static final int tab_btn_power=0x7f040055;
        public static final int tab_btn_settings=0x7f040054;
        public static final int tab_movies=0x7f04002f;
        public static final int tab_music=0x7f040009;
        public static final int tab_power=0x7f04004d;
        public static final int tab_settings=0x7f04003e;
        public static final int tab_title=0x7f040006;
        public static final int toggle_album_art=0x7f04003f;
        public static final int toggle_speaker_fill=0x7f04004b;
        public static final int top_bar=0x7f040004;
        public static final int vol_label=0x7f040020;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
}
